name: food_delivery_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  app_logger:
    path: packages/app_logger

  #?Logging
  talker_bloc_logger: ^4.4.1

  #?State Management
  hydrated_bloc: ^9.1.5
  flutter_bloc: ^8.1.6

  #?Utilities
  flutter_animate: ^4.5.0
  flutter_screenutil: ^5.9.3
  get_it: ^8.0.1
  go_router: ^14.3.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  json_annotation: ^4.9.0
  phosphor_flutter: ^2.1.0
  figma_squircle: ^0.5.3
  collection: ^1.18.0
  skeletonizer: ^1.4.2
  cached_network_image: ^3.4.1
  photo_view: ^0.15.0
  intl: ^0.20.1
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.13
  flutter_gen_runner: ^5.8.0
  very_good_analysis: ^6.0.0

flutter_gen:
  output: lib/core/assets/

  assets:
    enabled: true
    outputs:
      class_name: AppAssets
    exclude:
  fonts:
    enabled: true
    outputs:
      class_name: AppFonts
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/json/
  fonts:
    - family: SFPRO
      fonts:
        - asset: assets/fonts/SF-Pro-Display-Black.otf
          weight: 900
        - asset: assets/fonts/SF-Pro-Display-Bold.otf
          weight: 800
        - asset: assets/fonts/SF-Pro-Display-Heavy.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Display-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Display-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Display-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Display-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Display-Thin.otf
          weight: 200
        - asset: assets/fonts/SF-Pro-Display-Ultralight.otf
          weight: 100
